namespace Avalonia.Controls
{
    public class DataGridColumn : AvaloniaObject
    {
        public static readonly DirectProperty<DataGridColumn, object> HeaderProperty =
            AvaloniaProperty.RegisterDirect<DataGridColumn, object>(nameof(Header), o => o.Header, (o, v) => o.Header = v);

        public static readonly DirectProperty<DataGridColumn, bool> IsAutoGeneratedProperty =
            AvaloniaProperty.RegisterDirect<DataGridColumn, bool>(nameof(IsAutoGenerated), o => o.IsAutoGenerated, (o, v) => o.IsAutoGenerated = v);

        private object _header;
        private bool _isAutoGenerated;

        public DataGridColumn(ItemPropertyInfo itemProperty)
        {
            ItemProperty = itemProperty;
        }

        public ItemPropertyInfo ItemProperty { get; }

        public object Header
        {
            get { return _header; }
            set { SetAndRaise(HeaderProperty, ref _header, value); }
        }

        public bool IsAutoGenerated
        {
            get { return _isAutoGenerated; }
            set { SetAndRaise(IsAutoGeneratedProperty, ref _isAutoGenerated, value); }
        }
    }
}
